AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  CognitoUserMigrationAuthenticationTriggerEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handler
      Handler: userMigrationAuthenticationTriggerEvent.handler
      Runtime: nodejs14.x
      Environment:
        Variables:
          LDAP_URL: ''
          LDAP_ADMIN_DN: ''
          LDAP_ADMIN_PASSWORD: ''
          LDAP_USER_SEARCH_BASE: ''
          LDAP_USERNAME_ATTRIBUTE: ''

Outputs:
  CognitoUserMigrationAuthenticationTriggerEventLambdaFunction:
    Description: "CognitoUserMigrationAuthenticationTriggerEvent Lambda Function ARN"
    Value: !GetAtt CognitoUserMigrationAuthenticationTriggerEvent.Arn
